excel_file = open("data.xlsx","w")
print(excel_file)
excel_file.close()
append = open("data.xlsx","w")
append.write("\nLhendup: id 111")
append.write("\nDorji: id 112")
append.write("\nPema: id 113")
append.write("\nTshomo: id 114")
append.write("\nBozong: id 115")
append.close()
opened_file = open("data.xlsx","r")
print(opened_file.read())
opened_file.close()
name=input("enter a name: ")
with open("data.xlsx","r") as f:
    contents = f.read()
    if name in contents:
        print(name,"exists in the file.")
    else:
        print(name,"does not exist in the file.")
